import Head from 'next/head';
import Image from 'next/image';
import { Used } from '../components/Used';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a target="_blank" href="https://github.com/AlonMiz/next-js-reproduce" rel="noreferrer">
          Source code https://github.com/AlonMiz/next-js-reproduce
        </a>
        <br />

        <Used />
        <br />
        <a target="_blank" href="/api/1">
          get api/1
        </a>
        <br />
        <a target="_blank" href="/api/revalidate">
          revalidate api/1
        </a>
        <br />

        <a target="_blank" href="/api/files">
          get some files content
        </a>
      </main>
    </div>
  );
}
